2019-01-15T10:48:33|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_device.py", line 99, in set_rate
    self.stop_NI_DAQ_AO()
AttributeError: 'NI_DAQ_device' object has no attribute 'stop_NI_DAQ_AO'

