2019-01-14T11:02:35|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\aless\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\aless\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\aless\eclipse-workspace\nidaqmx_test\ni_hardware.py", line 28, in connect
    frequency=self.frequency.val, offset=self.offset.val, debug=self.debug_mode.val)
  File "C:\Users\aless\eclipse-workspace\nidaqmx_test\ni_device.py", line 20, in __init__
    self.startTask()
  File "C:\Users\aless\eclipse-workspace\nidaqmx_test\ni_device.py", line 26, in startTask
    self.task = nidaqmx.Task()
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\task.py", line 84, in __init__
    self._handle = lib_importer.task_handle(0)
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\_lib.py", line 178, in task_handle
    self._parse_typedefs()
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\_lib.py", line 241, in _parse_typedefs
    version = system.driver_version
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\system\system.py", line 73, in driver_version
    return DriverVersion(self._major_version, self._minor_version,
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\system\system.py", line 108, in _major_version
    cfunc = lib_importer.windll.DAQmxGetSysNIDAQMajorVersion
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\_lib.py", line 166, in windll
    self._import_lib()
  File "C:\Users\aless\Anaconda3\lib\site-packages\nidaqmx\_lib.py", line 209, in _import_lib
    windll = ctypes.windll.LoadLibrary(lib_name)
  File "C:\Users\aless\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\aless\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

