2019-01-14T16:27:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_hardware.py", line 28, in connect
    frequency=self.frequency.val, offset=self.offset.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_device.py", line 19, in __init__
    self.startTask()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_device.py", line 27, in startTask
    self.task.ao_channels.add_ao_voltage_chan(physical_channel=self.channel, min_val=0.0, max_val=5.0) #add an analog output channel
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\_task_modules\ao_channel_collection.py", line 191, in add_ao_voltage_chan
    check_for_error(error_code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: I/O type of the physical channel does not match the I/O type required for the virtual channel you are creating.
Physical Channel Name: pfi0
Virtual Channel Name: Dev2/pfi0
I/O Type Required for Virtual Channel: DAQmx_Val_AO

Task Name: _unnamedTask<0>

Status Code: -200430

