2019-01-15T11:07:50|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_device.py", line 100, in set_rate
    self.task.timing.cfg_samp_clk_timing(rate=self.send_rate) #change the frequency in send_rate
AttributeError: 'NI_DAQ_device' object has no attribute 'send_rate'

