2019-02-05T10:26:42|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\nidaqmx_test\ni_app.py", line 39, in <module>
    app = NI_App(sys.argv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_app.py", line 23, in setup
    self.add_hardware(NI_CO_hw(self))
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 80, in __init__
    self.setup()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_hardware.py", line 16, in setup
    board, terminals, trig=self.update_channels()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_hardware.py", line 77, in update_channels
    trig.append(trig.name)
AttributeError: 'TriggerUsage' object has no attribute 'append'

