2019-01-21T18:27:13|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_hardware.py", line 42, in connect
    trigger_source=self.trigger_source.val, trigger_edge=self.trigger_edge.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_device.py", line 23, in __init__
    self.Task()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_device.py", line 30, in Task
    self.task.co_channels.add_co_pulse_chan_freq(counter=self.channel, idle_state=nidaqmx.constants.Level.NO_CHANGE, initial_delay=0.0, freq=self.freq, duty_cycle=self.duty_cycle)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\_task_modules\co_channel_collection.py", line 101, in add_co_pulse_chan_freq
    check_for_error(error_code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: Requested value is not a supported value for this property. The property value may be invalid because it conflicts with another property.
Property: DAQmx_CO_Pulse_IdleState
Requested Value: DAQmx_Val_NoChange
Possible Values: DAQmx_Val_Low, DAQmx_Val_High
Channel Name: Dev2/ctr0

Task Name: _unnamedTask<0>

Status Code: -200077

