2019-01-21T13:07:34|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_hardware.py", line 42, in connect
    trigger_source=self.trigger_source.val, trigger_edge=self.trigger_edge.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_device.py", line 23, in __init__
    self.Task()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_co_device.py", line 30, in Task
    self.task.co_channels.add_co_pulse_chan_freq(counter=self.channel, idle_state=nidaqmx.constants.Level.LOW, freq=self.freq, duty_cycle=self.duty_cycle)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\_task_modules\co_channel_collection.py", line 101, in add_co_pulse_chan_freq
    check_for_error(error_code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nidaqmx\errors.py", line 127, in check_for_error
    raise DaqError(error_buffer.value.decode("utf-8"), error_code)
nidaqmx.errors.DaqError: I/O type of the physical channel does not match the I/O type required for the virtual channel you are creating.
Physical Channel Name: ao0
Virtual Channel Name: Dev2/ao0
I/O Type Required for Virtual Channel: DAQmx_Val_CO

Task Name: _unnamedTask<0>

Status Code: -200430

