2019-01-15T14:52:53|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\LabPrograms\Python\nidaqmx_test\ni_hardware.py", line 37, in connect
    frequency=self.frequency.val, offset=self.offset.val, debug=self.debug_mode.val)
  File "C:\LabPrograms\Python\nidaqmx_test\ni_device.py", line 16, in __init__
    "triangle": sp.triangle,
AttributeError: module 'scipy.signal' has no attribute 'triangle'

